[[headers]]
  for = "/*"
  [headers.values]
  Referrer-Policy = "origin-when-cross-origin"
  Permissions-Policy = "interest-cohort=()"
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  X-XSS-Protection = "1; mode=block"
  Content-Security-Policy = "upgrade-insecure-requests"
  
