[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://trusted-cdn.com; object-src 'none'"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permission-Policy = "camera=(), microphone=(), geolocation=(self), fullscreen=()"
    
  
